/*
 * generated by Xtext 2.10.0
 */
package net.technearts.tests

import com.google.inject.Inject
import net.technearts.timor.File
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(TimorInjectorProvider)
class TimorParsingTest{

	@Inject
	ParseHelper<File> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
