/*
 * generated by Xtext 2.10.0
 */
package net.technearts


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TimorStandaloneSetup extends TimorStandaloneSetupGenerated {

	def static void doSetup() {
		new TimorStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
