/**
 * generated by Xtext 2.10.0
 */
package net.technearts.ui;

import net.technearts.ui.AbstractTimorUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TimorUiModule extends AbstractTimorUiModule {
  public TimorUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
