/**
 * generated by Xtext 2.10.0
 */
package net.technearts.validation;

import net.technearts.validation.AbstractTimorValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TimorValidator extends AbstractTimorValidator {
}
