/**
 * generated by Xtext 2.10.0
 */
package net.technearts;

import net.technearts.TimorStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TimorStandaloneSetup extends TimorStandaloneSetupGenerated {
  public static void doSetup() {
    TimorStandaloneSetup _timorStandaloneSetup = new TimorStandaloneSetup();
    _timorStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
